# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_preReq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
